apiVersion: v1
kind: Pod

metadata:
  name: nginx-init-fail

spec:

  initContainers:

  - name: init-fail

    image: busybox

    command:
      - sh
      - -c
      - |
        echo "Erro? Agora já não"
        exit 0

  containers:

  - name: nginx

    image: nginx
