apiVersion: v1
kind: Pod

metadata:
  name: nginx-init

spec:

  initContainers:

  - name: init-message

    image: busybox

    command:
      - sh
      - -c
      - |
        echo "Preparing Pod..."
        sleep 10

  containers:

  - name: nginx

    image: nginx
