---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-api

resources:
  - ../../base

secretGenerator:
  - name: postgres-credentials
    envs:
      - secrets.env

generatorOptions:
  labels:
    app.kubernetes.io/name: devops-api-stack
    app.kubernetes.io/part-of: devops-api-stack
