---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-api

resources:
  - ../../base
  - ingress.yaml

secretGenerator:
  - name: postgres-credentials
    envs:
      - secrets.env

generatorOptions:
  labels:
    app.kubernetes.io/name: devops-api-stack
    app.kubernetes.io/part-of: devops-api-stack

images:
  - name: ghcr.io/limonne/devops-api-stack
    newTag: sha-8f1edea
