apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox
spec:
  containers:
  - name: nginx
    image: nginx

  - name: busybox
    image: busybox
    command:
      - sh
      - -c
      - |
        while true
        do
          echo "Busybox ativo..."
          sleep 10
        done
