---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: devops-api
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: devops-api-stack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: devops-api
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: devops-api
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: devops-api-stack
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: devops-api
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
