apiVersion: v1
kind: Pod

metadata:
  name: volume-test

spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"

    volumeMounts:
    - name: cache
      mountPath: /cache

  volumes:
  - name: cache
    emptyDir: {}
