apiVersion: v1

kind: Pod

metadata:
  name: pvc-dynamic-test

spec:

  containers:

  - name: busybox

    image: busybox

    command:
      - sleep
      - "3600"

    volumeMounts:

    - name: dados

      mountPath: /dados

  volumes:

  - name: dados

    persistentVolumeClaim:

      claimName: pvc-dynamic
