apiVersion: batch/v1
kind: CronJob

metadata:
  name: hello-cronjob

spec:

  schedule: "*/1 * * * *"

  successfulJobsHistoryLimit: 2

  failedJobsHistoryLimit: 1

  jobTemplate:

    spec:

      template:

        spec:

          restartPolicy: Never

          containers:

          - name: hello

            image: busybox

            command:

            - echo

            - "Hello from CronJob!"
