---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-api-stack
  namespace: argocd
spec:
  description: GitOps deployment for devops-api-stack

  sourceRepos:
    - https://github.com/limonne/devops-api-stack.git

  destinations:
    - namespace: devops-api
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
