---
name: CI

on:
  push:
  pull_request:

# Concurrency based on PR number ou reference for fallback
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-lint:
    uses: ./.github/workflows/lint.yml
    with: 
      python-version: "3.12"

  validate:
    needs: call-lint
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show project files
        run: ls -la

      - name: Check docker compose config
        run: docker compose config

      - name: Check python syntax
        run: python -m py_compile server.py

      - name: System Info
        run: |
          uname -a
          df -h
          free -h
          nproc

  build:
    needs: validate
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Docker build
        run: docker build -t devops-api-backend .

  healthcheck:
    needs: build
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Docker build
        run: docker build -t devops-api-backend .

      - name: Start containers
        run: docker compose up -d

      - name: Wait for services become healthy
        run: |
            for i in {1..12}; do
              if curl -fsS http://localhost:8080/api/health; then
                exit 0
              fi
              docker compose ps
              sleep 5
              done
              docker compose logs
              exit 1

      - name: Health Checks
        uses: ./.github/actions/healthchecks

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-debug-artifacts
          path: artifacts/

      - name: Cleanup all
        if: always()
        run: docker compose down -v
