name: Lint workflow

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version"
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: [python, yaml]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Setup Python dependencies
        uses: ./.github/actions/setup-python

      - name: Lint python
        if: matrix.linter == 'python'
        run: flake8 server.py

      - name: Lint yaml
        if: matrix.linter == 'yaml'
        run: yamllint docker-compose.yml
